### PR TITLE
Fix Method Handle Invocation

### PR DESCRIPTION
**Pull request by Sychic**
The current implementation of the method handle does not provide the correct signature. 
It's given `(UTextComponent,I)Object` when it wants `(GuiNewChat,MCITextComponent,I)V`

### CODE REVIEW

**Comment by Sychic** [comment]
Fixed the parts of the signature inside the parenthesis but it still wants an object return type for some reason.

**Comment by Johni0702** [comment]
> Fixed the parts of the signature inside the parenthesis but it still wants an object return type for some reason.

As far as I can tell, this is because of the null-safe call. That returns `T?` where `T` is the return type of the right side, null if the left side is null, therefore the right side is technically used in an expression context.
One way around that is to wrap the actual call in `apply`, which always returns `Unit` and therefore the `invokeExact` is correctly inferred as a statement:
```kotlin
    printChatMessageWithOptionalDeletion?.apply { invokeExact(textComponent, lineID) }
```
(ofc this also needs the arg fixes)

**Comment by LlamaLad7** [comment]
I thought this was more to do with our outdated Kotlin version. Even with the old code, the bytecode uses `V` in the Kotlin bytecode viewer, it's only the compiled class which has the problem.

**Comment by Sychic** [comment]
Huh well that does seem to fix it. Learning something new every day. 😃

**Comment by LlamaLad7** [comment]
> Which bytecode viewer are you talking about?

Tools > Show Kotlin Bytecode when in a source file

**Review by LlamaLad7 — APPROVED** [review]

**Pull request merged**
